services:
    corebundle.servicesqlqueries:
        class: CoreBundle\Service\ServiceSqlQueries
        arguments:
            - "@doctrine"

    corebundle.servicecallofoffer:
        class: CoreBundle\Service\ServiceCallOfOffer
        arguments:
            - "@doctrine"

    authentication.handler.login_success_handler:
        class:  CoreBundle\Security\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']
