# app/config/security.yml

security:
  encoders:
    CoreBundle\Entity\User: bcrypt

  role_hierarchy:
    ROLE_VIWAMETAL: ROLE_USER
    ROLE_PROVIDER: ROLE_USER
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      id: fos_user.user_provider.username

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main_login:
      pattern: ^/login$
      anonymous: true



    reinit:
      pattern: ^/reinit
      anonymous: true
    creation_viwa_user:
      pattern: ^/createViwaUser
      anonymous: true
#    creation_provider1:
#      pattern: ^/synchro2
#      anonymous: true
#    creation_provider2:
#      pattern: ^/synchro3
#      anonymous: true

    main:
      pattern: ^/
      anonymous: false
      provider: main
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        success_handler: authentication.handler.login_success_handler

      logout:
        path: fos_user_security_logout
        target: fos_user_security_login
      remember_me:
        secret:   %secret%



  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel:https }
