<?php

namespace CoreBundle\Repository;

/**
 * CallOfOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallOfOfferRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllCoo()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM CoreBundle:CallOfOffer c')
           ->getResult();
    }

    public function getAllCooInProgress($inProgress)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM CoreBundle:CallOfOffer c WHERE c.inProgress = :inProgress')
            ->setParameter('inProgress', $inProgress)
            ->getResult();
    }

}
