<?php

namespace CoreBundle\Repository;

/**
 * CallOfOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallOfOfferRepository extends \Doctrine\ORM\EntityRepository
{
        public function getTagOfCoobyPropositionId($idProp){

            return 0;
        }

}
