<?php

namespace CoreBundle\Repository;

/**
 * ViwaUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViwaUserRepository extends \Doctrine\ORM\EntityRepository
{
}
